
import { GoogleGenAI, Modality, Chat } from '@google/genai';

const getAi = () => new GoogleGenAI({ apiKey: process.env.API_KEY as string });

/**
 * Generates a new image based on an original image and a style prompt.
 */
export const generateStyledImage = async (base64Image: string, mimeType: string, style: string): Promise<string> => {
  const ai = getAi();
  const model = 'gemini-2.5-flash-image';
  
  const response = await ai.models.generateContent({
    model,
    contents: {
      parts: [
        { inlineData: { data: base64Image, mimeType } },
        { text: `Reimagine this room in a ${style} interior design style. Maintain the room's core layout and architectural features like windows and doors, but change the furniture, color palette, lighting, and decor to fit the style.` },
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  const firstPart = response.candidates?.[0]?.content?.parts?.[0];
  if (firstPart && firstPart.inlineData) {
    return firstPart.inlineData.data;
  }
  
  throw new Error('No image was generated by the API.');
};

/**
 * Edits an existing image based on a text prompt.
 */
export const editImage = async (base64Image: string, mimeType: string, prompt: string): Promise<string> => {
  const ai = getAi();
  const model = 'gemini-2.5-flash-image';
  
  const response = await ai.models.generateContent({
    model,
    contents: {
      parts: [
        { inlineData: { data: base64Image, mimeType } },
        { text: prompt },
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  const firstPart = response.candidates?.[0]?.content?.parts?.[0];
  if (firstPart && firstPart.inlineData) {
    return firstPart.inlineData.data;
  }
  
  throw new Error('No image was returned from the edit request.');
};

/**
 * Sends a message to the chat and gets a response.
 */
export const sendMessage = async (chat: Chat, message: string): Promise<string> => {
    const response = await chat.sendMessage({ message });
    return response.text;
};
